// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/hyperOutportBlocks/hyperOutportBlocks.proto

package hyperOutportBlocks

import (
	data "github.com/multiversx/mx-chain-ws-connector-template-go/data"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HyperOutportBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OutportBlock                *data.MetaOutportBlock        `protobuf:"bytes,1,opt,name=OutportBlock,proto3" json:"OutportBlock,omitempty"`
	NotarizedHeadersOutportData []*NotarizedHeaderOutportData `protobuf:"bytes,2,rep,name=NotarizedHeadersOutportData,proto3" json:"NotarizedHeadersOutportData,omitempty"`
}

func (x *HyperOutportBlock) Reset() {
	*x = HyperOutportBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HyperOutportBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperOutportBlock) ProtoMessage() {}

func (x *HyperOutportBlock) ProtoReflect() protoreflect.Message {
	mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperOutportBlock.ProtoReflect.Descriptor instead.
func (*HyperOutportBlock) Descriptor() ([]byte, []int) {
	return file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescGZIP(), []int{0}
}

func (x *HyperOutportBlock) GetOutportBlock() *data.MetaOutportBlock {
	if x != nil {
		return x.OutportBlock
	}
	return nil
}

func (x *HyperOutportBlock) GetNotarizedHeadersOutportData() []*NotarizedHeaderOutportData {
	if x != nil {
		return x.NotarizedHeadersOutportData
	}
	return nil
}

type NotarizedHeaderOutportData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NotarizedHeaderHash string                  `protobuf:"bytes,1,opt,name=NotarizedHeaderHash,proto3" json:"NotarizedHeaderHash,omitempty"`
	OutportBlock        *data.ShardOutportBlock `protobuf:"bytes,2,opt,name=OutportBlock,proto3" json:"OutportBlock,omitempty"`
}

func (x *NotarizedHeaderOutportData) Reset() {
	*x = NotarizedHeaderOutportData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotarizedHeaderOutportData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotarizedHeaderOutportData) ProtoMessage() {}

func (x *NotarizedHeaderOutportData) ProtoReflect() protoreflect.Message {
	mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotarizedHeaderOutportData.ProtoReflect.Descriptor instead.
func (*NotarizedHeaderOutportData) Descriptor() ([]byte, []int) {
	return file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescGZIP(), []int{1}
}

func (x *NotarizedHeaderOutportData) GetNotarizedHeaderHash() string {
	if x != nil {
		return x.NotarizedHeaderHash
	}
	return ""
}

func (x *NotarizedHeaderOutportData) GetOutportBlock() *data.ShardOutportBlock {
	if x != nil {
		return x.OutportBlock
	}
	return nil
}

type BlockHashRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *BlockHashRequest) Reset() {
	*x = BlockHashRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHashRequest) ProtoMessage() {}

func (x *BlockHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHashRequest.ProtoReflect.Descriptor instead.
func (*BlockHashRequest) Descriptor() ([]byte, []int) {
	return file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescGZIP(), []int{2}
}

func (x *BlockHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BlockNonceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce uint32 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *BlockNonceRequest) Reset() {
	*x = BlockNonceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNonceRequest) ProtoMessage() {}

func (x *BlockNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNonceRequest.ProtoReflect.Descriptor instead.
func (*BlockNonceRequest) Descriptor() ([]byte, []int) {
	return file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescGZIP(), []int{3}
}

func (x *BlockNonceRequest) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_api_hyperOutportBlocks_hyperOutportBlocks_proto protoreflect.FileDescriptor

var file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f,
	0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x4f, 0x75,
	0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x66,
	0x69, 0x72, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb5, 0x01, 0x0a, 0x11, 0x48, 0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x3b, 0x0a, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x63, 0x0a, 0x1b, 0x4e, 0x6f, 0x74, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x74, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x1b, 0x4e, 0x6f, 0x74,
	0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x4f, 0x75, 0x74,
	0x70, 0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x22, 0x8c, 0x01, 0x0a, 0x1a, 0x4e, 0x6f, 0x74,
	0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70,
	0x6f, 0x72, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x30, 0x0a, 0x13, 0x4e, 0x6f, 0x74, 0x61, 0x72,
	0x69, 0x7a, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x4e, 0x6f, 0x74, 0x61, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12, 0x3c, 0x0a, 0x0c, 0x4f, 0x75, 0x74,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x4f, 0x75, 0x74,
	0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0c, 0x4f, 0x75, 0x74, 0x70, 0x6f,
	0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x26, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x29, 0x0a, 0x11, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x32, 0xc2, 0x01, 0x0a, 0x18, 0x48,
	0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x48, 0x79,
	0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70,
	0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x1b, 0x47, 0x65,
	0x74, 0x48, 0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x42, 0x79, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x48, 0x79, 0x70, 0x65,
	0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x00, 0x42,
	0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x75,
	0x6c, 0x74, 0x69, 0x76, 0x65, 0x72, 0x73, 0x78, 0x2f, 0x6d, 0x78, 0x2d, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x2d, 0x77, 0x73, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x74,
	0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2d, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68,
	0x79, 0x70, 0x65, 0x72, 0x4f, 0x75, 0x74, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescOnce sync.Once
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescData = file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDesc
)

func file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescGZIP() []byte {
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescOnce.Do(func() {
		file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescData)
	})
	return file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDescData
}

var file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_hyperOutportBlocks_hyperOutportBlocks_proto_goTypes = []interface{}{
	(*HyperOutportBlock)(nil),          // 0: proto.HyperOutportBlock
	(*NotarizedHeaderOutportData)(nil), // 1: proto.NotarizedHeaderOutportData
	(*BlockHashRequest)(nil),           // 2: proto.BlockHashRequest
	(*BlockNonceRequest)(nil),          // 3: proto.BlockNonceRequest
	(*data.MetaOutportBlock)(nil),      // 4: proto.MetaOutportBlock
	(*data.ShardOutportBlock)(nil),     // 5: proto.ShardOutportBlock
}
var file_api_hyperOutportBlocks_hyperOutportBlocks_proto_depIdxs = []int32{
	4, // 0: proto.HyperOutportBlock.OutportBlock:type_name -> proto.MetaOutportBlock
	1, // 1: proto.HyperOutportBlock.NotarizedHeadersOutportData:type_name -> proto.NotarizedHeaderOutportData
	5, // 2: proto.NotarizedHeaderOutportData.OutportBlock:type_name -> proto.ShardOutportBlock
	2, // 3: proto.HyperOutportBlockService.GetHyperOutportBlockByHash:input_type -> proto.BlockHashRequest
	3, // 4: proto.HyperOutportBlockService.GetHyperOutportBlockByNonce:input_type -> proto.BlockNonceRequest
	0, // 5: proto.HyperOutportBlockService.GetHyperOutportBlockByHash:output_type -> proto.HyperOutportBlock
	0, // 6: proto.HyperOutportBlockService.GetHyperOutportBlockByNonce:output_type -> proto.HyperOutportBlock
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_hyperOutportBlocks_hyperOutportBlocks_proto_init() }
func file_api_hyperOutportBlocks_hyperOutportBlocks_proto_init() {
	if File_api_hyperOutportBlocks_hyperOutportBlocks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HyperOutportBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotarizedHeaderOutportData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockHashRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockNonceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hyperOutportBlocks_hyperOutportBlocks_proto_goTypes,
		DependencyIndexes: file_api_hyperOutportBlocks_hyperOutportBlocks_proto_depIdxs,
		MessageInfos:      file_api_hyperOutportBlocks_hyperOutportBlocks_proto_msgTypes,
	}.Build()
	File_api_hyperOutportBlocks_hyperOutportBlocks_proto = out.File
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_rawDesc = nil
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_goTypes = nil
	file_api_hyperOutportBlocks_hyperOutportBlocks_proto_depIdxs = nil
}
