name: Go linter
on:
  pull_request:
    branches: [main, feat/*]
    types: [opened, ready_for_review]
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    name: golangci linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17.6
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --timeout 10m0s --max-issues-per-linter 0 --max-same-issues 0 --print-issued-lines

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
